### ISSUE TITLE
安卓客户端源码可否提供参考

### ISSUE THREAD

**Issue by chensk1** [yioMe/node_wx_alipay_personalPay#3]
目前我自己使用的是安卓+java后台的开发的这一套系统 但是安卓客户端监听通知的线程会跑死 请问如何避免？

**Comment by yioMe** [comment]
无法理解上下文，不明白你说的“跑死”是什么意思。

**Comment by yioMe** [comment]
许久未回复关闭此Iss

**Comment by chensk1** [comment]
抱歉 ,就是一直开着,到后面 微信和支付宝的俄推送不会被监听了 就无法向后台发送订单成功的请求
