### ISSUE TITLE
https://github.com/yioMe/node_wx_alipay_personalPay/issues/3

### ISSUE THREAD

**Issue by chensk1** [yioMe/node_wx_alipay_personalPay#5]
这个问题 就是 我一直开着系统,他时间长了 推送过来 就监听不到了  就无法向后台发订单成功的请求 。我刚才回复了 最近有点忙 网站没打开

**Comment by chensk1** [comment]
核心代码 
`package acatch.kaiwo.com.notifycatch;

import android.app.ActivityManager;
import android.app.Service;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.IBinder;

import java.util.List;

/**
 * Created by chensk on 2018/8/8.
 */

public class NotificationCollectorMonitorService extends Service {
    @Override
    public void onCreate() {
        super.onCreate();
        ensureCollectorRunning();
    }
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        return START_STICKY;
    }
    //确认NotificationMonitor是否开启
    private void ensureCollectorRunning() {
        ComponentName collectorComponent = new ComponentName(this, NotificationMonitorService.class);
        ActivityManager manager = (ActivityManager) getSystemService(Context.ACTIVITY_SERVICE);
        boolean collectorRunning = false;
        List<ActivityManager.RunningServiceInfo> runningServices = manager.getRunningServices(Integer.MAX_VALUE);
        if (runningServices == null ) {
            return;
        }
        for (ActivityManager.RunningServiceInfo service : runningServices) {
            if (service.service.equals(collectorComponent)) {
                if (service.pid == android.os.Process.myPid() ) {
                    collectorRunning = true;
                }
            }
        }
        if (collectorRunning) {
            return;
        }
        toggleNotificationListenerService();
    }
    //重新开启NotificationMonitor
    private void toggleNotificationListenerService() {
        ComponentName thisComponent = new ComponentName(this,  NotificationMonitorService.class);
        PackageManager pm = getPackageManager();
        pm.setComponentEnabledSetting(thisComponent, PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
        pm.setComponentEnabledSetting(thisComponent, PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP);

    }
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}`

`package acatch.kaiwo.com.notifycatch;

import android.content.Intent;
import android.os.Handler;
import android.os.Message;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;
import android.util.Log;
import android.widget.Toast;

/**
 * Created by chensk on 2018/8/6.
 */



import android.annotation.SuppressLint;
import android.app.Notification;
import android.os.Bundle;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;
import android.util.Log;

import com.zhy.http.okhttp.OkHttpUtils;
import com.zhy.http.okhttp.cookie.CookieJarImpl;
import com.zhy.http.okhttp.cookie.store.PersistentCookieStore;
import com.zhy.http.okhttp.https.HttpsUtils;

import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import acatch.kaiwo.com.notifycatch.http.ApiService;
import acatch.kaiwo.com.notifycatch.http.LoggerInterceptorRefactoring;
import acatch.kaiwo.com.notifycatch.http.RetMap;
import acatch.kaiwo.com.notifycatch.http.RetrofitClient;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;
import rx.Subscriber;
import rx.android.schedulers.AndroidSchedulers;
import rx.schedulers.Schedulers;

@SuppressLint("NewApi")
public class NotificationMonitorService extends NotificationListenerService {
    String merId = "100001";
    // 在收到消息时触发
    MyApplication application;





    public static String getnumber(String str) {
        // 需要取整数和小数的字符串

        // 控制正则表达式的匹配行为的参数(小数)
        Pattern p = Pattern.compile("(\\d+\\.\\d+)");
        //Matcher类的构造方法也是私有的,不能随意创建,只能通过Pattern.matcher(CharSequence input)方法得到该类的实例.
        Matcher m = p.matcher(str);
        //m.find用来判断该字符串中是否含有与"(\\d+\\.\\d+)"相匹配的子串
        if (m.find()) {
            //如果有相匹配的,则判断是否为null操作
            //group()中的参数：0表示匹配整个正则，1表示匹配第一个括号的正则,2表示匹配第二个正则,在这只有一个括号,即1和0是一样的
            str = m.group(1) == null ? "" : m.group(1);
        } else {
            //如果匹配不到小数，就进行整数匹配
            p = Pattern.compile("(\\d+)");
            m = p.matcher(str);
            if (m.find()) {
                //如果有整数相匹配
                str = m.group(1) == null ? "" : m.group(1);
            } else {
                //如果没有小数和整数相匹配,即字符串中没有整数和小数，就设为空
                str = "";
            }
        }
        return str;

    }

    @Override
    public void onNotificationPosted(StatusBarNotification sbn) {


        // TODO Auto-generated method stub
        Bundle extras = sbn.getNotification().extras;
        // 获取接收消息APP的包名
        String notificationPkg = sbn.getPackageName();
        // 获取接收消息的抬头
        String notificationTitle = extras.getString(Notification.EXTRA_TITLE);
        // 获取接收消息的内容
        String notificationText = extras.getString(Notification.EXTRA_TEXT);
        Log.i("XSL_Test", "Notification posted " + notificationTitle + " & " + notificationText);
        application = (MyApplication) getApplication();

        if(notificationTitle!=null) {


            if (notificationTitle.equals("支付宝通知")) {
                // 成功收款0.01元。享免费提现等更多专属服务，点击查看
                // data=data.replace("[","");
                String money = getnumber(notificationText);
                Log.i("Money_income", money);
                postMoney(merId, money, "01");
            }
            if (notificationTitle.equals("微信收款助手")) {
                // 成功收款0.01元。享免费提现等更多专属服务，点击查看
                // data=data.replace("[","");
                String money = getnumber(notificationText);
                Log.i("Money_income", money);
                postMoney(merId, money, "02");
            }

        }
    }

    private void postMoney(String merId, String money,String payType) {
        Log.i("进入http post","merId="+merId+" money="+money);
        HashMap map = new HashMap();
        map.put("merId",merId);
        map.put("money",money);
        map.put("payType",payType);
        if(application.apiService==null) {
           application.network();

        }
        application.apiService.notify(map)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Subscriber<RetMap>() {
                    @Override
                    public void onCompleted() {

                    }
                    @Override
                    public void onError(Throwable e) {
                        e.printStackTrace();
                    }
                    @Override
                    public void onNext(RetMap retMap) {
                       if(retMap.status==1){
                            Log.e("回调消息","回调成功");
                        }
                    }
                });

    }

    // 在删除消息时触发
    @Override
    public void onNotificationRemoved(StatusBarNotification sbn) {
        // TODO Auto-generated method stub
        Bundle extras = sbn.getNotification().extras;
        // 获取接收消息APP的包名
        String notificationPkg = sbn.getPackageName();
        // 获取接收消息的抬头
        String notificationTitle = extras.getString(Notification.EXTRA_TITLE);
        // 获取接收消息的内容
        String notificationText = extras.getString(Notification.EXTRA_TEXT);
        Log.i("XSL_Test", "Notification removed " + notificationTitle + " & " + notificationText);
    }
}
`

**Comment by chensk1** [comment]
`package acatch.kaiwo.com.notifycatch;

import android.content.Intent;
import android.os.Handler;
import android.os.Message;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;
import android.util.Log;
import android.widget.Toast;

/**
 * Created by chensk on 2018/8/6.
 */



import android.annotation.SuppressLint;
import android.app.Notification;
import android.os.Bundle;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;
import android.util.Log;

import com.zhy.http.okhttp.OkHttpUtils;
import com.zhy.http.okhttp.cookie.CookieJarImpl;
import com.zhy.http.okhttp.cookie.store.PersistentCookieStore;
import com.zhy.http.okhttp.https.HttpsUtils;

import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import acatch.kaiwo.com.notifycatch.http.ApiService;
import acatch.kaiwo.com.notifycatch.http.LoggerInterceptorRefactoring;
import acatch.kaiwo.com.notifycatch.http.RetMap;
import acatch.kaiwo.com.notifycatch.http.RetrofitClient;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;
import rx.Subscriber;
import rx.android.schedulers.AndroidSchedulers;
import rx.schedulers.Schedulers;

@SuppressLint("NewApi")
public class NotificationMonitorService extends NotificationListenerService {
    String merId = "100001";
    // 在收到消息时触发
    MyApplication application;





    public static String getnumber(String str) {
        // 需要取整数和小数的字符串

        // 控制正则表达式的匹配行为的参数(小数)
        Pattern p = Pattern.compile("(\\d+\\.\\d+)");
        //Matcher类的构造方法也是私有的,不能随意创建,只能通过Pattern.matcher(CharSequence input)方法得到该类的实例.
        Matcher m = p.matcher(str);
        //m.find用来判断该字符串中是否含有与"(\\d+\\.\\d+)"相匹配的子串
        if (m.find()) {
            //如果有相匹配的,则判断是否为null操作
            //group()中的参数：0表示匹配整个正则，1表示匹配第一个括号的正则,2表示匹配第二个正则,在这只有一个括号,即1和0是一样的
            str = m.group(1) == null ? "" : m.group(1);
        } else {
            //如果匹配不到小数，就进行整数匹配
            p = Pattern.compile("(\\d+)");
            m = p.matcher(str);
            if (m.find()) {
                //如果有整数相匹配
                str = m.group(1) == null ? "" : m.group(1);
            } else {
                //如果没有小数和整数相匹配,即字符串中没有整数和小数，就设为空
                str = "";
            }
        }
        return str;

    }

    @Override
    public void onNotificationPosted(StatusBarNotification sbn) {


        // TODO Auto-generated method stub
        Bundle extras = sbn.getNotification().extras;
        // 获取接收消息APP的包名
        String notificationPkg = sbn.getPackageName();
        // 获取接收消息的抬头
        String notificationTitle = extras.getString(Notification.EXTRA_TITLE);
        // 获取接收消息的内容
        String notificationText = extras.getString(Notification.EXTRA_TEXT);
        Log.i("XSL_Test", "Notification posted " + notificationTitle + " & " + notificationText);
        application = (MyApplication) getApplication();

        if(notificationTitle!=null) {


            if (notificationTitle.equals("支付宝通知")) {
                // 成功收款0.01元。享免费提现等更多专属服务，点击查看
                // data=data.replace("[","");
                String money = getnumber(notificationText);
                Log.i("Money_income", money);
                postMoney(merId, money, "01");
            }
            if (notificationTitle.equals("微信收款助手")) {
                // 成功收款0.01元。享免费提现等更多专属服务，点击查看
                // data=data.replace("[","");
                String money = getnumber(notificationText);
                Log.i("Money_income", money);
                postMoney(merId, money, "02");
            }

        }
    }

    private void postMoney(String merId, String money,String payType) {
        Log.i("进入http post","merId="+merId+" money="+money);
        HashMap map = new HashMap();
        map.put("merId",merId);
        map.put("money",money);
        map.put("payType",payType);
        if(application.apiService==null) {
           application.network();

        }
        application.apiService.notify(map)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Subscriber<RetMap>() {
                    @Override
                    public void onCompleted() {

                    }
                    @Override
                    public void onError(Throwable e) {
                        e.printStackTrace();
                    }
                    @Override
                    public void onNext(RetMap retMap) {
                       if(retMap.status==1){
                            Log.e("回调消息","回调成功");
                        }
                    }
                });

    }

    // 在删除消息时触发
    @Override
    public void onNotificationRemoved(StatusBarNotification sbn) {
        // TODO Auto-generated method stub
        Bundle extras = sbn.getNotification().extras;
        // 获取接收消息APP的包名
        String notificationPkg = sbn.getPackageName();
        // 获取接收消息的抬头
        String notificationTitle = extras.getString(Notification.EXTRA_TITLE);
        // 获取接收消息的内容
        String notificationText = extras.getString(Notification.EXTRA_TEXT);
        Log.i("XSL_Test", "Notification removed " + notificationTitle + " & " + notificationText);
    }
}
`

**Comment by chensk1** [comment]
`
public class NotificationCollectorMonitorService extends Service {
    @Override
    public void onCreate() {
        super.onCreate();
        ensureCollectorRunning();
    }
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        return START_STICKY;
    }
    //确认NotificationMonitor是否开启
    private void ensureCollectorRunning() {
        ComponentName collectorComponent = new ComponentName(this, NotificationMonitorService.class);
        ActivityManager manager = (ActivityManager) getSystemService(Context.ACTIVITY_SERVICE);
        boolean collectorRunning = false;
        List<ActivityManager.RunningServiceInfo> runningServices = manager.getRunningServices(Integer.MAX_VALUE);
        if (runningServices == null ) {
            return;
        }
        for (ActivityManager.RunningServiceInfo service : runningServices) {
            if (service.service.equals(collectorComponent)) {
                if (service.pid == android.os.Process.myPid() ) {
                    collectorRunning = true;
                }
            }
        }
        if (collectorRunning) {
            return;
        }
        toggleNotificationListenerService();
    }
    //重新开启NotificationMonitor
    private void toggleNotificationListenerService() {
        ComponentName thisComponent = new ComponentName(this,  NotificationMonitorService.class);
        PackageManager pm = getPackageManager();
        pm.setComponentEnabledSetting(thisComponent, PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
        pm.setComponentEnabledSetting(thisComponent, PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP);

    }
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}`

**Comment by chensk1** [comment]
`public class NotificationMonitorService extends NotificationListenerService {
    String merId = "100001";
    // 在收到消息时触发
    MyApplication application;





    public static String getnumber(String str) {
        // 需要取整数和小数的字符串

        // 控制正则表达式的匹配行为的参数(小数)
        Pattern p = Pattern.compile("(\\d+\\.\\d+)");
        //Matcher类的构造方法也是私有的,不能随意创建,只能通过Pattern.matcher(CharSequence input)方法得到该类的实例.
        Matcher m = p.matcher(str);
        //m.find用来判断该字符串中是否含有与"(\\d+\\.\\d+)"相匹配的子串
        if (m.find()) {
            //如果有相匹配的,则判断是否为null操作
            //group()中的参数：0表示匹配整个正则，1表示匹配第一个括号的正则,2表示匹配第二个正则,在这只有一个括号,即1和0是一样的
            str = m.group(1) == null ? "" : m.group(1);
        } else {
            //如果匹配不到小数，就进行整数匹配
            p = Pattern.compile("(\\d+)");
            m = p.matcher(str);
            if (m.find()) {
                //如果有整数相匹配
                str = m.group(1) == null ? "" : m.group(1);
            } else {
                //如果没有小数和整数相匹配,即字符串中没有整数和小数，就设为空
                str = "";
            }
        }
        return str;

    }

    @Override
    public void onNotificationPosted(StatusBarNotification sbn) {


        // TODO Auto-generated method stub
        Bundle extras = sbn.getNotification().extras;
        // 获取接收消息APP的包名
        String notificationPkg = sbn.getPackageName();
        // 获取接收消息的抬头
        String notificationTitle = extras.getString(Notification.EXTRA_TITLE);
        // 获取接收消息的内容
        String notificationText = extras.getString(Notification.EXTRA_TEXT);
        Log.i("XSL_Test", "Notification posted " + notificationTitle + " & " + notificationText);
        application = (MyApplication) getApplication();

        if(notificationTitle!=null) {


            if (notificationTitle.equals("支付宝通知")) {
                // 成功收款0.01元。享免费提现等更多专属服务，点击查看
                // data=data.replace("[","");
                String money = getnumber(notificationText);
                Log.i("Money_income", money);
                postMoney(merId, money, "01");
            }
            if (notificationTitle.equals("微信收款助手")) {
                // 成功收款0.01元。享免费提现等更多专属服务，点击查看
                // data=data.replace("[","");
                String money = getnumber(notificationText);
                Log.i("Money_income", money);
                postMoney(merId, money, "02");
            }

        }
    }

    private void postMoney(String merId, String money,String payType) {
        Log.i("进入http post","merId="+merId+" money="+money);
        HashMap map = new HashMap();
        map.put("merId",merId);
        map.put("money",money);
        map.put("payType",payType);
        if(application.apiService==null) {
           application.network();

        }
        application.apiService.notify(map)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Subscriber<RetMap>() {
                    @Override
                    public void onCompleted() {

                    }
                    @Override
                    public void onError(Throwable e) {
                        e.printStackTrace();
                    }
                    @Override
                    public void onNext(RetMap retMap) {
                       if(retMap.status==1){
                            Log.e("回调消息","回调成功");
                        }
                    }
                });

    }

    // 在删除消息时触发
    @Override
    public void onNotificationRemoved(StatusBarNotification sbn) {
        // TODO Auto-generated method stub
        Bundle extras = sbn.getNotification().extras;
        // 获取接收消息APP的包名
        String notificationPkg = sbn.getPackageName();
        // 获取接收消息的抬头
        String notificationTitle = extras.getString(Notification.EXTRA_TITLE);
        // 获取接收消息的内容
        String notificationText = extras.getString(Notification.EXTRA_TEXT);
        Log.i("XSL_Test", "Notification removed " + notificationTitle + " & " + notificationText);
    }
}
`

**Comment by chensk1** [comment]
代码插入这个有问题。。正片插入不进来

**Comment by yioMe** [comment]
应该是你开发的app进程被系统杀掉了，另外就是你app的问题在项目里提iss不太合适，联系邮箱a@yio.me
