### ISSUE TITLE
支付宝和微信收到款，服务器端都没有收到通知。

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [yioMe/node_wx_alipay_personalPay#8]

**Comment by yioMe** [comment]
你好，请看下邮件，小米手机目前无法监听到信息。

**Comment by dreamfit** [comment]
thank u。
我已自己排查解决。是数据库表字段自己建的不对。后来把教程重头到尾重新来一遍之后，正常了。

**Comment by dreamfit** [comment]
thank u。
我已自己排查解决。是数据库表字段自己建的不对。后来把教程重头到尾重新来一遍之后，正常了。
